### ISSUE TITLE
 Ctrl + Left and Ctrl + Shift + Left do no match

### ISSUE THREAD

**Issue by duzenko** [alefragnani/vscode-delphi-keybindings#17] opened 2020-11-14 07:21 UTC
Steps to Reproduce:

1. In a .ts file. have a line of code
```
		ctx.lineWidth = element.strokeWidth ?? 1;
```
2. Put cursor at the start of `strokeWidth`
3. Press Ctrl + Left. Cursor goes to the end of `element`
4. Go back to the start of `strokeWidth` and press Ctrl + Shift + Left
5. Cursor goes to the start of `element`

This is frustrating and counter-intuitive.

**Comment by duzenko** [comment] 2020-11-14 07:21
I would prefer both going to the start of element, which is default in VSCode

**Comment by alefragnani** [comment] 2020-11-17 15:34
Hi @duzenko ,

I think you are saying, in fact _which is default in Delphi_ right? Because the extension idea is to make VS Code shortcuts _looks like Delphi_ 😁 

What I could see is, Delphi always go to the start of the word, no matter if you use `Shift` or not. But the extension, when you don't use `Shift`, goes to the end/start/end/start of the word, which does not mimic Delphi behaviour.

Thanks for reporting.

**Comment by duzenko** [comment] 2020-11-17 15:38
> 
> 
> Hi @duzenko ,
> 
> I think you are saying, in fact _which is default in Delphi_ right? Because the extension idea is to make VS Code shortcuts _looks like Delphi_ 😁
> 

Well, ideally yes, of course
Coincidentally, both VSCode and Delphi seem to go to the start by default.

**Comment by alefragnani** [comment] 2020-11-17 15:44
> Coincidentally, both VSCode and Delphi seem to go to the start by default.
Weird. On my MacOS, using `Ctrl + Left` does the start/end/start/end/start of the word scenario, even the extension using the `cursorWordStartLeft` VS Code command.

I'll test again on a Windows PC later.

**Comment by duzenko** [comment] 2020-11-17 15:47
https://github.com/microsoft/vscode/issues/110303

**Comment by alefragnani** [comment] 2020-11-17 21:44
Just noticed the difference between MacOS and Windows is caused by the `Ctrl` / `Cmd` difference, and in MacOS I should use `Cmd`.

And yes, there was an error on the Keybinding. It should use a different command for `Ctrl + Left/Right ` to mimic Delphi behavior.

It will be fixed soon.

Stay tuned

**Closed** 2020-11-18 01:20 UTC
Labels: bug
